### ISSUE TITLE
[BUG] Strip Empty Splits

### ISSUE THREAD

**Issue by NWPlayer123** [encounter/decomp-toolkit#79]
### Game Name

Animal Crossing

### Game Version

GAFE01

### Description

When first importing Animal Crossing from its symbol maps, under splits.txt/dataobject.obj, it lists a bunch of "empty" splits
```	.text       start:0x002D0FAC end:0x002D0FAC```
Is there any reason not to strip these, especially when there's 3200+ duplicates? The only thing I could think of would be nonstandard alignment requirements (e.g. if a .text section needs .align 32). I think this is a consequence of blindly following a symbol map, since it does list the empty .text sections in there.
```  002d0fac 000000 002d0fac  1 .text 	dataobject.obj```

**Comment by encounter** [comment]
Empty splits are meaningful in some cases: particularly games built with `-sym on` and a map file. The map will preserve the section symbols for each generated `.text` section, even if all the functions were stripped from it, which helps match the weak function ordering.

AC's `dataobject.obj` is definitely an outlier in this regard. I assume their assembler left an empty `.text` section in each object. So that's what you're seeing in the map. Since these empty sections don't have any real meaning, it makes sense to remove them.

Since removing these is quite simple to write a script for, I'm not sure this needs to be a dtk feature.
